name: Nix Check

on:
  push:
  pull_request:

jobs:
  nix-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: cachix/install-nix-action@v27
      
      - name: Run nix fmt
        run: nix fmt
      
      - name: Run nix flake check
        run: nix flake check